name: CI
permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 7
    runs-on: ubuntu-22.04
    strategy:
      matrix: 
        include:
          - version: "3.10"
            target: py310
          - version: "3.11"
            target: py311
          - version: "3.12"
            target: py312
          - version: "3.13"
            target: py313
          - version: "3.14"
            target: py314
          - version: "3.13"
            target: pep8
          - version: "3.10"
            target: mypy
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python 🔧
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.version }}

      - name: Build 🔧 & Test 🔍
        run: |
          pip install tox
          tox -e ${{ matrix.target }}
