name: upload release to PyPI
on:
  release:
    types:
      - published

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13

      - name: Install build
        run: |
          pip install tox
          tox -e build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
